openapi: "3.0.0"
info:
  title: Simple API overview
  version: v1
paths:
  /users:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: 'users'
      responses:
        default:
          description: Default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserList"
              examples:
                success:
                  value: [
                             {
                                 "id": "1",
                                 "name": "user-1"
                             },
                             {
                                 "id": "2",
                                 "name": "user-2"
                             },
                             {
                                 "id": "3",
                                 "name": "user-3"
                             },
                             {
                                 "id": "4",
                                 "name": "user-4"
                             }
                         ]

components:
  schemas:
    User:
      properties:
        id:
          type: string
        name:
          type: string
    UserList:
          properties:
            products:
              description: Contains the list of users
              type: array
              items:
          $ref: "#/components/schemas/User"